name:                oblivious-transfer
version:             0.1.0
github:              adjoint-io/oblivious-transfer
license:             Apache
maintainer:          Adjoint Inc (info@adjoint.io)
category:            Cryptography

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/oblivious-transfer#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  oblivious-transfer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oblivious-transfer

tests:
  oblivious-transfer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oblivious-transfer
