name:                oblivious-transfer
version:             0.1.0
github:              adjoint-io/oblivious-transfer
synopsis:            An implementation of the Oblivious Transfer protocol in Haskell
license:             Apache
maintainer:          Adjoint Inc (info@adjoint.io)
category:            Cryptography

extra-source-files:
- README.md
- ChangeLog.md
description:         Please see the README on GitHub at <https://github.com/adjoint-io/oblivious-transfer#readme>

dependencies:
- base                 >= 4.7    && < 5
- bytestring           >= 0.10.8 && < 0.11
- elliptic-curve       >= 0.3.0  && < 0.4
- galois-field         >= 1.0    && < 1.1
- memory               >= 0.14.0 && < 0.16
- MonadRandom          >= 0.5.1  && < 0.6
- protolude            >= 0.2.3  && < 0.3
- random               >= 1.1    && < 1.2
- SHA                  >= 1.6.4  && < 1.7

library:
  source-dirs: src

  ghc-options:
    -fwarn-tabs
    -fwarn-incomplete-patterns
    -fwarn-incomplete-record-updates
    -fwarn-redundant-constraints
    -fwarn-implicit-prelude
    -fwarn-overflowed-literals
    -fwarn-orphans
    -fwarn-identities
    -fwarn-dodgy-exports
    -fwarn-dodgy-imports
    -fwarn-duplicate-exports
    -fwarn-overlapping-patterns
    -fwarn-missing-fields
    -fwarn-missing-methods
    -fwarn-missing-signatures
    -fwarn-noncanonical-monad-instances
    -fwarn-unused-pattern-binds
    -fwarn-unused-type-patterns
    -fwarn-unrecognised-pragmas
    -fwarn-wrong-do-bind
    -fno-warn-name-shadowing
    -fno-warn-unused-binds
    -fno-warn-unused-matches
    -fno-warn-unused-do-bind

  default-extensions:
    - LambdaCase
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    - FlexibleInstances

  exposed-modules:
    - OT

tests:
  oblivious-transfer-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oblivious-transfer
    - QuickCheck               >= 2.12 && <2.13
    - tasty                    >= 1.2  && <1.3
    - tasty-discover           >= 4.1  && <4.3
    - tasty-hunit              >= 0.10 && <0.11
    - tasty-quickcheck         >= 0.10 && <0.11
    default-extensions:
    - LambdaCase
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    - FlexibleInstances
